import PokemonDataCheck from "@/components/pokemon-data-check/pokemon-data-check";
import { ToastProvider } from "@/components/ui/Toast/toast-context";
import { QueryProvider } from "@/lib/query-client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="https://www.pokemoncenter.com/favicon.ico" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <QueryProvider>
          <ToastProvider>
            {children}
            <PokemonDataCheck />
          </ToastProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
